---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: platform
  name: camunda-bpm
  namespace: camunda-bpm
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/component: platform
  type: ClusterIP
